### ISSUE TITLE
toNumber.js:64 Uncaught Error: Module parse failed: Unexpected character '�' (1:2) 

### ISSUE THREAD

**Issue by WildXBird** [LinusU/node-lodepng#9]
toNumber.js:64 Uncaught Error: Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by LinusU** [comment]
There is no file named `toNumber.js` in this module, why do you think that this module is the source of the error?

The error message seems to indicate that you are using WebPack? This module is a native Node.js module and thus won't work in the browser...

Happy to reopen if it turns out this was a problem with this library!
